### ISSUE TITLE
improve  add point (+ adding pictures)

### ISSUE THREAD

**Issue by meagrivera** [OpenGridMap/pgis#4]
on the editing it should be able to have a drag and drop. kind of like add point and then give the chance to add pole or transformer or substation.
This is not trivial... since a substation is a polygon .
We need to discuss this.

**Comment by klausschreiber** [comment]
To do:
- sending picture to server with ajax
- generate unique submission_id
- fix bugs

**Comment by klausschreiber** [comment]
everything fixed
To do:
How to check if user is logged in / how to log in user
